const actionTypes = {
  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  LOAD_IMMERSIONS: 'LOAD_IMMERSIONS',
  LOAD_DIVE: 'LOAD_DIVE',
  CREATE_IMMERSION: 'CREATE_IMMERSION',
  SAVE_IMMERSION: 'SAVE_IMMERSION',
  DELETE_IMMERSION: 'DELETE_IMMERSION'

};

export default actionTypes;
