const actionTypes = {
  USER_SING_IN: 'USER_SING_IN',
  USER_SING_OUT: 'USER_SING_OUT',
  LOAD_IMMERSIONS: 'LOAD_IMMERSIONS',
  CREATE_IMMERSION: 'CREATE_IMMERSION',
  SAVE_IMMERSION: 'SAVE_IMMERSION',
  DELETE_IMMERSION: 'DELETE_IMMERSION'

};

export default actionTypes;
